language: ruby
rvm:
  - 1.9.2
  - 1.9.3
before_script:
  - cp config/database.example.yml config/database.yml
  - mysql -e 'create database bradley_online_test;'
  - rake db:migrate
  - rake db:seed
  - rake db:test:prepare
  - cp config/application.example.yml config/application.yml
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "export CI=yes"
script: 
  - bundle exec rspec spec --format documentation --colour
  - bundle exec rspec spec --format documentation --colour --tag js